{% set version = "0.1.18" %}

package:
  name: pytoml
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytoml/pytoml-{{ version }}.tar.gz
  sha256: dae3c4e31d09eb06a6076d671f2281ee5d2c43cbeae16599c3af20881bb818ac

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pytoml
    - pytoml.parser
    - pytoml.writer

about:
  home: https://github.com/avakar/pytoml
  license: MIT
  license_file: LICENSE
  summary: 'A TOML-0.4.0 parser/writer for Python.'

extra:
  recipe-maintainers:
    - pkgw
