{% set name = "pytoml" %}
{% set version = "0.1.15" %}
{% set sha256 = "de7e42a852dcf4c8b757b59898dee06ecca80ddaf607b3b2011cc9279f8edf99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.org/packages/source/p/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pytoml

about:
  home: http://github.com/avakar/pytoml
  license: MIT
  license_file: LICENSE
  summary: 'A TOML-0.4.0 parser/writer for Python.'

extra:
  recipe-maintainers:
    - pkgw
