travis:
  secure:
    BINSTAR_TOKEN: jAxG79upSThO3HUgSNmAa4eXy22fqbmIlgg0MSXcxTzpomVHLjXt7s7oZ6pBfxfW4kOXyGXifbhmuHff9BydkzMqyM1QMkR9DZAMs+wSQ4mhHoaxFNy9cuvEMkyH4Dbqbyw+zWivejekUUDdvCsmJ0s1MDPto/0Kbgdn6Xr7NQWiqCDiOme7yM5I10mfviBvbRknPqJ8crhfBZMM7+Q2g+ssv9I8UXgqlnI8pBfOOTXbe/x5vmpfuLDoXFwqBTss/6Rhq2ZxVOnuKpu0kRm/ZpdEx+mvcMPSU4L1Ggh9X9h672v3rQu4TmB8HJ/QAzAmd0pd6Eg4fqUfqOXqhsfLK4soI8ar8BqxP35wLmZavQJiSVHN39TRwo/6TVvu8YAo+KU/+4sEG4QPiKQrAQJPA3lJFE3mDxm2CgTzuLooSO2V5M8MZBp6evbfT3CLXUyuB/hxqcYzeDJY7tsyhT88gSkKTySNx9hklkBDBWrq8/RqlwkRsNJUbaMijcKnEdAmcHSW3YAzM9f846+q0aXQRaDaEH2rM6jEWaraP7zYev6RVcaKysLnqkqeOpdSdBzIyMjvJzE7TNTpvZFZOgtrDV3rDR9J0gjLtFdRPT6lSN0sAfKUvEXoGTpqWpzVSDGdDnGOQmLkccudHW/SDhAoDuqX7fRPX/uKWiyt0blVNC8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
