travis:
  secure:
    BINSTAR_TOKEN: wIwDYvzhOQEne9GcF7oOcbHTU1qYYD+8rEsQI8Mri6bLtn3UX3mzylzP2dZglxoq86hK5AvA1KBgg5xW7+rJgQvIq6b9K+HbwpGF0NoBokFzGLPWdLH8GIkBTYwAZ/4hQ8HfNskB6PYC7KhGp7sBCyM22hOmBcH5eUI6X0rDqSTZdBtTDOP/vhrjlblL7d1AHfi6oIvDCOh39BwSdlU90y7BNVg7sHEcFdS5CZoH9YhSHFAUvmlSKjyApPe67K2sjCQHSf+3ZEtiXJYz8mgE2i2YQLACPaHiHGBOlaTOdCb/AMCnWvIq9e1IO4v3yknJ+N5YQcOxP+btTj9vq7OAtvyCG7/bytvPiSpuaY8rwOhIiECKwzFjGNNhMpfyYRWwinKRh+KN+x8Vnjr/3scYzQQ26z4hcC6QHtMYyO5S9jaoehFlVBWaAdKAt/itSHrbY/G+tCnxrgpKLOiYrACtDmej1xs6Anh0C+odUAbwjmzVhr4+39Qbms3JSpQb4bu+so/NN+TRLRaBwbePcOh5/QMQ4HY1ZvTwcoES336Ie3nQ9+NCT/vgXoI4dFOrn9I1G9jHijrjaLoRvkqlwzmoK6H2MsWCvgoD1wdfJxKLIh1/JeEpq1VlH3j2jkSlviKsbFLsfXFoxba3AGg/2kS3nMNNbQz0hv2MPIygCb8q82I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
