travis:
  secure:
    BINSTAR_TOKEN: e1n2UL27JC6uw5HXKhtgVxUxMWWsmy382ME0oV4N08jZfeR/NxWzt0we5g5vJRMI5ygosGYYFgmRb9QGnB62GCPBt4mcVyT5MwJ/UmKyXM4WFdkRaXm/7zAuBtisIMOtMtZVAxtntLsauXTmt/81iBZShBByHTLjOIVH5yS1AIF1iSzpbvc0udVfjQ4gXM3QtO2ACP4aLmRMTvblPwm0szwaHuu9y8ViYbpmwIc4RZKsyrPcjSECFJtOBYEWaD/C7U5ukaxZaFIcpNKbXCfrqpP58MObGMy8k2BX+PbgnvrE4j9BbF212kmB7WyRVmXdH3/KEuiTMtfbFH2WU8jFNXe2tDyFb8ueryhryZ0reCYn7n547VvS8omXtrDZSeHSSQgalEKRSZi/FhOJ9oJUXk08jm8ecnfIPeiFK94usYKbQ5zRTh425CIkxnAnM1Z2pMogzcDK0DXGD/SKGajw45sKQORaUsNKasfZSePA0WLgkPKqEzsIH9f267t3/FhXfSlrzDOVJQY4otdReIlEQ2SIT8RLp5q6YMe8QqRU1Wyl7fWN8IgMedDIn3Pj1W45Hmg95drPyx2+J6lKiBjJi4TcwDV4mKj9YUgPQJwPTfwzMDO/pYuN16S38md0Cus9ogQklBivTn33qlob+FoWCdXVekQ6hJmxbua9bfNPWyQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
